### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by alexlii1971** [leewillis77/wc-structured-data-option-3#2]
Hello,

I check the post at
https://github.com/woocommerce/woocommerce/issues/16006
https://github.com/woocommerce/woocommerce/issues/17471
https://github.com/woocommerce/woocommerce/issues/17471

and it seems quite an older bug.

and also used the plugin at https://github.com/leewillis77/wc-structured-data-option-3

but it did not fix the issue, please check the screenshot of the issue in Google merchant center: https://storage.googleapis.com/support-forums-api/attachment/thread-168342951-6027605215510943442.png

and please check the structured data at https://validator.schema.org/#url=https%3A%2F%2Flovcour.com%2Fgenuine-leather-shoulder-bag-womens-luxury-handbags-fashion-crossbody-bags-totes-bag%2F%3Fattribute_pa_color%3Dwhite%26attribute_pa_material%3Dgenuine-leather%26attribute_pa_size%3D10-inch

There is no change after using that plugin, right?

And it seems Google still gets the parent lowprice as sales price and highprice as regular price.

Could you please let us know how to resolve the issue, please?

**Comment by leewillis77** [comment]
Hi; 

The work on this has been rolled into a feature in the [WooCommerce Google Product Feed](https://woocommerce.com/products/google-product-feed) plugin for further work. If you're a customer of that extension please open a ticket on WooCommerce.com so we can offer you detailed advice. 

We can't really provide support beyond that, but I will note that you're not using the WooCommerce structured data, but structured data provided by a third party plugin, so I'd suggest you contact their support team for queries about the structured data they produce (or disable that).
